//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Share_Common.proto
namespace Share_Common
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Stuff_Vector3")]
  public partial class Stuff_Vector3 : global::ProtoBuf.IExtensible
  {
    public Stuff_Vector3() {}
    

    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }

    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }

    private float _z = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Stuff_Message")]
  public partial class Stuff_Message : global::ProtoBuf.IExtensible
  {
    public Stuff_Message() {}
    

    private Share_Common.Stuff_Message.MC_Type _type_t = Share_Common.Stuff_Message.MC_Type.MC_EnterScene;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type_t", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Share_Common.Stuff_Message.MC_Type.MC_EnterScene)]
    public Share_Common.Stuff_Message.MC_Type type_t
    {
      get { return _type_t; }
      set { _type_t = value; }
    }

    private int _source = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"source", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int source
    {
      get { return _source; }
      set { _source = value; }
    }

    private int _target = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"target", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int target
    {
      get { return _target; }
      set { _target = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _paras = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"paras", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> paras
    {
      get { return _paras; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MC_Type")]
    public enum MC_Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MC_EnterScene", Value=1)]
      MC_EnterScene = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Stuff_Message_Queue")]
  public partial class Stuff_Message_Queue : global::ProtoBuf.IExtensible
  {
    public Stuff_Message_Queue() {}
    
    private readonly global::System.Collections.Generic.List<Share_Common.Stuff_Message> _contents = new global::System.Collections.Generic.List<Share_Common.Stuff_Message>();
    [global::ProtoBuf.ProtoMember(1, Name=@"contents", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Share_Common.Stuff_Message> contents
    {
      get { return _contents; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Stuff_Item")]
  public partial class Stuff_Item : global::ProtoBuf.IExtensible
  {
    public Stuff_Item() {}
    
    private int _ItemId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ItemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ItemId
    {
      get { return _ItemId; }
      set { _ItemId = value; }
    }

    private Share_Common.Item_Type _type_t = Share_Common.Item_Type.Data_Item_Medichine;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type_t", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Share_Common.Item_Type.Data_Item_Medichine)]
    public Share_Common.Item_Type type_t
    {
      get { return _type_t; }
      set { _type_t = value; }
    }

    private bool _Bind = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Bind", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool Bind
    {
      get { return _Bind; }
      set { _Bind = value; }
    }

    private int _BaseId = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"BaseId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int BaseId
    {
      get { return _BaseId; }
      set { _BaseId = value; }
    }

    private int _AddonId = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"AddonId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int AddonId
    {
      get { return _AddonId; }
      set { _AddonId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Stuff_Inventory")]
  public partial class Stuff_Inventory : global::ProtoBuf.IExtensible
  {
    public Stuff_Inventory() {}
    
    private readonly global::System.Collections.Generic.List<Share_Common.Stuff_Item> _Items = new global::System.Collections.Generic.List<Share_Common.Stuff_Item>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Share_Common.Stuff_Item> Items
    {
      get { return _Items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Stuff_Account")]
  public partial class Stuff_Account : global::ProtoBuf.IExtensible
  {
    public Stuff_Account() {}
    

    private Share_Common.C2S_Proto_Type _type_t = Share_Common.C2S_Proto_Type.Proto_Stuff_Account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type_t", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Share_Common.C2S_Proto_Type.Proto_Stuff_Account)]
    public Share_Common.C2S_Proto_Type type_t
    {
      get { return _type_t; }
      set { _type_t = value; }
    }
    private string _UserName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"UserName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string UserName
    {
      get { return _UserName; }
      set { _UserName = value; }
    }

    private string _PassWord = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"PassWord", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string PassWord
    {
      get { return _PassWord; }
      set { _PassWord = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Stuff_GetPlayer")]
  public partial class Stuff_GetPlayer : global::ProtoBuf.IExtensible
  {
    public Stuff_GetPlayer() {}
    

    private Share_Common.C2S_Proto_Type _type_t = Share_Common.C2S_Proto_Type.Proto_Stuff_GetPlayer;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type_t", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Share_Common.C2S_Proto_Type.Proto_Stuff_GetPlayer)]
    public Share_Common.C2S_Proto_Type type_t
    {
      get { return _type_t; }
      set { _type_t = value; }
    }
    private string _UserName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"UserName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string UserName
    {
      get { return _UserName; }
      set { _UserName = value; }
    }

    private int _PlayerId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"PlayerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int PlayerId
    {
      get { return _PlayerId; }
      set { _PlayerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Stuff_Login")]
  public partial class Stuff_Login : global::ProtoBuf.IExtensible
  {
    public Stuff_Login() {}
    

    private Share_Common.C2S_Proto_Type _type_t = Share_Common.C2S_Proto_Type.Proto_Stuff_Login;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type_t", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Share_Common.C2S_Proto_Type.Proto_Stuff_Login)]
    public Share_Common.C2S_Proto_Type type_t
    {
      get { return _type_t; }
      set { _type_t = value; }
    }
    private string _UserName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"UserName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string UserName
    {
      get { return _UserName; }
      set { _UserName = value; }
    }

    private int _PlayerId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"PlayerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int PlayerId
    {
      get { return _PlayerId; }
      set { _PlayerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Stuff_Player")]
  public partial class Stuff_Player : global::ProtoBuf.IExtensible
  {
    public Stuff_Player() {}
    

    private Share_Common.S2C_Proto_Type _type_t = Share_Common.S2C_Proto_Type.Proto_Stuff_Player;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type_t", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Share_Common.S2C_Proto_Type.Proto_Stuff_Player)]
    public Share_Common.S2C_Proto_Type type_t
    {
      get { return _type_t; }
      set { _type_t = value; }
    }
    private int _PlayerId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"PlayerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PlayerId
    {
      get { return _PlayerId; }
      set { _PlayerId = value; }
    }

    private Share_Common.Stuff_Vector3 _Position = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Share_Common.Stuff_Vector3 Position
    {
      get { return _Position; }
      set { _Position = value; }
    }

    private Share_Common.Creature_Variety _Variety = Share_Common.Creature_Variety.CV_Player;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Variety", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Share_Common.Creature_Variety.CV_Player)]
    public Share_Common.Creature_Variety Variety
    {
      get { return _Variety; }
      set { _Variety = value; }
    }

    private int _NationId = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"NationId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int NationId
    {
      get { return _NationId; }
      set { _NationId = value; }
    }

    private int _MafiaId = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"MafiaId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int MafiaId
    {
      get { return _MafiaId; }
      set { _MafiaId = value; }
    }
    private readonly global::System.Collections.Generic.List<Share_Common.Stuff_Inventory> _Inventory = new global::System.Collections.Generic.List<Share_Common.Stuff_Inventory>();
    [global::ProtoBuf.ProtoMember(7, Name=@"Inventory", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Share_Common.Stuff_Inventory> Inventory
    {
      get { return _Inventory; }
    }
  
    private readonly global::System.Collections.Generic.List<Share_Common.Stuff_Limit> _Limits = new global::System.Collections.Generic.List<Share_Common.Stuff_Limit>();
    [global::ProtoBuf.ProtoMember(8, Name=@"Limits", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Share_Common.Stuff_Limit> Limits
    {
      get { return _Limits; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Stuff_Players")]
  public partial class Stuff_Players : global::ProtoBuf.IExtensible
  {
    public Stuff_Players() {}
    

    private Share_Common.S2C_Proto_Type _type_t = Share_Common.S2C_Proto_Type.Proto_Stuff_Players;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type_t", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Share_Common.S2C_Proto_Type.Proto_Stuff_Players)]
    public Share_Common.S2C_Proto_Type type_t
    {
      get { return _type_t; }
      set { _type_t = value; }
    }
    private string _UserName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"UserName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string UserName
    {
      get { return _UserName; }
      set { _UserName = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _Players = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"Players", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> Players
    {
      get { return _Players; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Stuff_Limit")]
  public partial class Stuff_Limit : global::ProtoBuf.IExtensible
  {
    public Stuff_Limit() {}
    

    private int _LimitId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"LimitId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int LimitId
    {
      get { return _LimitId; }
      set { _LimitId = value; }
    }

    private int _StartTime = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"StartTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int StartTime
    {
      get { return _StartTime; }
      set { _StartTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Stuff_Creatures")]
  public partial class Stuff_Creatures : global::ProtoBuf.IExtensible
  {
    public Stuff_Creatures() {}
    
    private readonly global::System.Collections.Generic.List<Share_Common.Stuff_Creature> _contents = new global::System.Collections.Generic.List<Share_Common.Stuff_Creature>();
    [global::ProtoBuf.ProtoMember(1, Name=@"contents", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Share_Common.Stuff_Creature> contents
    {
      get { return _contents; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Stuff_Creature")]
  public partial class Stuff_Creature : global::ProtoBuf.IExtensible
  {
    public Stuff_Creature() {}
    

    private int _CreatureId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"CreatureId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int CreatureId
    {
      get { return _CreatureId; }
      set { _CreatureId = value; }
    }

    private Share_Common.Creature_Variety _Variety = Share_Common.Creature_Variety.CV_Null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Variety", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Share_Common.Creature_Variety.CV_Null)]
    public Share_Common.Creature_Variety Variety
    {
      get { return _Variety; }
      set { _Variety = value; }
    }

    private Share_Common.Stuff_Vector3 _Position = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Share_Common.Stuff_Vector3 Position
    {
      get { return _Position; }
      set { _Position = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Item_Medichine")]
  public partial class Item_Medichine : global::ProtoBuf.IExtensible
  {
    public Item_Medichine() {}
    

    private Share_Common.Item_Type _type_t = Share_Common.Item_Type.Data_Item_Medichine;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type_t", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Share_Common.Item_Type.Data_Item_Medichine)]
    public Share_Common.Item_Type type_t
    {
      get { return _type_t; }
      set { _type_t = value; }
    }
    private uint _tid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"tid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint tid
    {
      get { return _tid; }
      set { _tid = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private uint _cool_time = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"cool_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cool_time
    {
      get { return _cool_time; }
      set { _cool_time = value; }
    }

    private uint _cool_type = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"cool_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cool_type
    {
      get { return _cool_type; }
      set { _cool_type = value; }
    }

    private int _mode = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mode
    {
      get { return _mode; }
      set { _mode = value; }
    }

    private int _time = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Item_Mine")]
  public partial class Item_Mine : global::ProtoBuf.IExtensible
  {
    public Item_Mine() {}
    

    private Share_Common.Item_Type _type_t = Share_Common.Item_Type.Data_Item_Mine;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type_t", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Share_Common.Item_Type.Data_Item_Mine)]
    public Share_Common.Item_Type type_t
    {
      get { return _type_t; }
      set { _type_t = value; }
    }
    private uint _tid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"tid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint tid
    {
      get { return _tid; }
      set { _tid = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private uint _cool_time = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"cool_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cool_time
    {
      get { return _cool_time; }
      set { _cool_time = value; }
    }

    private uint _cool_type = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"cool_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cool_type
    {
      get { return _cool_type; }
      set { _cool_type = value; }
    }

    private int _mode = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mode
    {
      get { return _mode; }
      set { _mode = value; }
    }

    private int _time = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Config_Path")]
  public partial class Config_Path : global::ProtoBuf.IExtensible
  {
    public Config_Path() {}
    

    private string _path = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string path
    {
      get { return _path; }
      set { _path = value; }
    }

    private string _svn_path = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"svn_path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string svn_path
    {
      get { return _svn_path; }
      set { _svn_path = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Config_Limit")]
  public partial class Config_Limit : global::ProtoBuf.IExtensible
  {
    public Config_Limit() {}
    

    private int _TId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"TId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int TId
    {
      get { return _TId; }
      set { _TId = value; }
    }

    private Share_Common.Config_Limit.Clear_Time _type_t = Share_Common.Config_Limit.Clear_Time.Year;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type_t", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Share_Common.Config_Limit.Clear_Time.Year)]
    public Share_Common.Config_Limit.Clear_Time type_t
    {
      get { return _type_t; }
      set { _type_t = value; }
    }

    private int _LimitTimes = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"LimitTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int LimitTimes
    {
      get { return _LimitTimes; }
      set { _LimitTimes = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Clear_Time")]
    public enum Clear_Time
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Year", Value=1)]
      Year = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Month", Value=2)]
      Month = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Day", Value=3)]
      Day = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Hour", Value=4)]
      Hour = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"Creature_Variety")]
    public enum Creature_Variety
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CV_Null", Value=1)]
      CV_Null = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CV_Player", Value=2)]
      CV_Player = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CV_NPC", Value=3)]
      CV_NPC = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Server_State")]
    public enum Server_State
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SS_Starting", Value=1)]
      SS_Starting = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SS_Started", Value=2)]
      SS_Started = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SS_Working", Value=3)]
      SS_Working = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SS_Closing", Value=4)]
      SS_Closing = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SS_Closed", Value=5)]
      SS_Closed = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"C2S_Proto_Type")]
    public enum C2S_Proto_Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Proto_Stuff_Client_Begin", Value=1)]
      Proto_Stuff_Client_Begin = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Proto_Stuff_Account", Value=2)]
      Proto_Stuff_Account = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Proto_Stuff_GetPlayer", Value=3)]
      Proto_Stuff_GetPlayer = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Proto_Stuff_Login", Value=4)]
      Proto_Stuff_Login = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"S2C_Proto_Type")]
    public enum S2C_Proto_Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Proto_Stuff_Server_Begin", Value=1)]
      Proto_Stuff_Server_Begin = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Proto_Stuff_Player", Value=2)]
      Proto_Stuff_Player = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Proto_Stuff_Players", Value=3)]
      Proto_Stuff_Players = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Item_Type")]
    public enum Item_Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Data_Item_Medichine", Value=1)]
      Data_Item_Medichine = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Data_Item_Mine", Value=2)]
      Data_Item_Mine = 2
    }
  
}