// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Drawing;
using GameServer.Logic;

namespace Terrain
{
	/*
	 * Slice in terrain.
	 */
	public class Slice
	{
		//public List<Player> m_PlayerList = new List<Player>();

		private Point m_Point;

		public Slice ()
		{
		}

		public Slice(Point point)
		{
			this.m_Point = point;
		}

		public Slice(int x, int z)
		{
			this.m_Point = new Point(x, z);
		}

		public Point GetPosition()
		{
			return this.m_Point;
		}

		/*
		 * Get 9 slices nearby included himself but excluded right 3 slices.
		 */
		public List<Slice> Get9Slices()
		{
			List<Slice> slices = new List<Slice> ();

			for (int i = -1; i < 1; ++i) 
			{
				for (int k = -1; k < 1; ++k) 
				{
					Slice slice = new Slice(GetPosition().X + i, GetPosition().Y + k);
					slices.Add(slice);
				}
			}
			return slices;
		}

		// End of class Slice
	}
}

