// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.IO;

/**
 * 
 * Provide functions for changing types or values.
 * 
 * This file is special for clients and servers.
 * 
 * @author lazy
 *
 */
namespace GameServer.Share
{
	public class UtilTools
	{
		/**
		 * 
		 * 将 Int 转为 byte[]
		 * @param intVal
		 * @return
		 * 
		 */
		public static byte[] IntToBytes(int intVal) 
		{   
			byte[] result = new byte[4];   
			result[3] = (byte)((intVal >> 24) & 0xFF);
			result[2] = (byte)((intVal >> 16) & 0xFF);
			result[1] = (byte)((intVal >> 8) & 0xFF); 
			result[0] = (byte)(intVal & 0xFF);
			return result;
		}
		/**
		 * 
		 * 将 Stream 转成 byte[] 
		 *
		 */
		public static byte[] StreamToBytes(Stream stream) 
		{ 
			byte[] bytes = new byte[stream.Length]; 
			stream.Read(bytes, 0, bytes.Length); 

			stream.Seek(0, SeekOrigin.Begin); 		// 设置当前流的位置为流的开始 
			return bytes; 
		} 

		/**
		 * 
		 * 将 byte[] 转成 Stream
		 *
		 */
		public static Stream BytesToStream(byte[] bytes) 
		{ 
			Stream stream = new MemoryStream(bytes); 
			return stream; 
		} 
		// End of class UtilTools
	}	
}

